EMPTY = 0
FULL = 1

ALIVE_ANT_CEL = 2
DEAD_ANT_CEL = 1
EMPTY_CEL = 0

ALIVE_ANTS = 10
DEAD_ANTS = 500

MATRIX_LENGTH = 50
TOTAL_MATRIX_CELS = MATRIX_LENGTH*MATRIX_LENGTH

QUANTITY_OF_ITERATIONS = 20000